const data = [{type:'铝板',e_t:'aluminium plate',prompt:['2A12铝板','5052铝板','5083铝板','6063铝板','6082铝板','7075铝板'],
                second_classify:[
                {serise:'1系',product:[
                    {
                        name:'1050',
                        texture:'工业纯铝',
                        ply:['H12','H14']
                    },
                    {
                        name:'1060',
                        texture:'工业纯铝',
                        ply:['H14','H24']
                    }
                ]},
                {serise:'2系',product:[
                    {
                        name:'2017',
                        texture:'军工硬铝',
                        ply:['T3','T4']
                    },
                    {
                        name:'2024',
                        texture:'军工硬铝',
                        ply:['T3','T4']
                    },
                    {
                        name:'2A12',
                        texture:'军工硬铝',
                        ply:['T3','T4']
                    }
                ]},
                {serise:'3系',product:[
                    {
                        name:'3003',
                        texture:'防锈铝合金',
                        ply:['H14','H24']
                    },
                    {
                        name:'3A21',
                        texture:'防锈铝合金',
                        ply:['H14','H112']
                    }
                ]},
                {serise:'5系',product:[
                    {
                        name:'5052',
                        texture:'耐腐蚀铝镁合金',
                        ply:['H32','H112']
                    },
                    {
                        name:'5083',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    },
                    {
                        name:'5754',
                        texture:'耐腐蚀铝镁合金',
                        ply:['H22','H111']
                    },
                    {
                        name:'5A02',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    },
                    {
                        name:'5A05',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    },
                    {
                        name:'5A06',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    }
                ]},
                {serise:'6系',product:[
                    {
                        name:'6061',
                        texture:'工业硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'6063',
                        texture:'工业硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'6082',
                        texture:'工业硬铝',
                        ply:['T6','T651']
                    }
                ]},
                {serise:'7系',product:[
                    {
                        name:'7050',
                        texture:'航空超硬铝',
                        ply:['T7451']
                    },
                    {
                        name:'7075',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'7A04',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'7A09',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    }
                ]}
            ]},
            {type:'铝棒',e_t:'aluminium rod',prompt:['2024铝棒','2A12铝棒','5083铝棒','6061铝棒','6082铝棒','7075铝棒'],
                second_classify:[
                {serise:'1系',product:[
                    {
                        name:'1050',
                        texture:'工业纯铝',
                        ply:['O','H112']
                    },
                    {
                        name:'1060',
                        texture:'工业纯铝',
                        ply:['O','H112']
                    }
                ]},
                {serise:'2系',product:[
                    {
                        name:'2017',
                        texture:'军工硬铝',
                        ply:['T3','T4']
                    },
                    {
                        name:'2024',
                        texture:'军工硬铝',
                        ply:['T3','T4']
                    },
                    {
                        name:'2A12',
                        texture:'军工硬铝',
                        ply:['T3','T4']
                    }
                ]},
                {serise:'3系',product:[
                    {
                        name:'3003',
                        texture:'防锈铝合金',
                        ply:['O','H112']
                    },
                    {
                        name:'3A21',
                        texture:'防锈铝合金',
                        ply:['O','H112']
                    }
                ]},
                {serise:'5系',product:[
                    {
                        name:'5052',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    },
                    {
                        name:'5083',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    },
                    {
                        name:'5754',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H111']
                    },
                    {
                        name:'5A02',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    },
                    {
                        name:'5A05',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    },
                    {
                        name:'5A06',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    }
                ]},
                {serise:'6系',product:[
                    {
                        name:'6061',
                        texture:'工业硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'6063',
                        texture:'工业硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'6082',
                        texture:'工业硬铝',
                        ply:['T6','T651']
                    }
                ]},
                {serise:'7系',product:[
                    {
                        name:'7050',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'7075',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'7A04',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'7A09',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    }
                ]}
            ]},
            {type:'铝卷',e_t:'aluminium roll',prompt:['2A12铝卷','5052铝卷','5083铝卷','6063铝卷','6084铝卷','7075铝卷'],
                second_classify:[
                {serise:'1系',product:[
                    {
                        name:'1050',
                        texture:'工业纯铝',
                        ply:['H14','H24']
                    },
                    {
                        name:'1060',
                        texture:'工业纯铝',
                        ply:['H14','H24']
                    },
                ]},
                {serise:'2系',product:[
                    {
                        name:'2024',
                        texture:'军工硬铝',
                        ply:['T3','T4']
                    },
                    {
                        name:'2A12',
                        texture:'军工硬铝',
                        ply:['O','T4']
                    }
                ]},
                {serise:'3系',product:[
                    {
                        name:'3003',
                        texture:'防锈铝合金',
                        ply:['H14','H24']
                    },
                    {
                        name:'3A21',
                        texture:'防锈铝合金',
                        ply:['O','H24']
                    }
                ]},
                {serise:'5系',product:[
                    {
                        name:'5052',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H32']
                    },
                    {
                        name:'5083',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H111']
                    },
                    {
                        name:'5754',
                        texture:'耐腐蚀铝镁合金',
                        ply:['H22','H111']
                    },
                    {
                        name:'5A02',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H32']
                    }
                ]},
                {serise:'6系',product:[
                    {
                        name:'6061',
                        texture:'工业硬铝',
                        ply:['O','T6']
                    },
                    {
                        name:'6063',
                        texture:'工业硬铝',
                        ply:['O','T6']
                    }
                ]},
                {serise:'7系',product:[
                    {
                        name:'7075',
                        texture:'航空超硬铝',
                        ply:['O','T6']
                    }
                ]}
            ]},
            {type:'铝管',e_t:'aluminium pipe',prompt:['2024铝管','2A12铝管','6061铝管','6063铝管','6082铝管','7075铝管'],
                second_classify:[
                {serise:'1系',product:[
                    {
                        name:'1050',
                        texture:'工业纯铝',
                        ply:['O','H112']
                    },
                    {
                        name:'1060',
                        texture:'工业纯铝',
                        ply:['O','H112']
                    }
                ]},
                {serise:'2系',product:[
                    {
                        name:'2017',
                        texture:'军工硬铝',
                        ply:['T3','T4']
                    },
                    {
                        name:'2024',
                        texture:'军工硬铝',
                        ply:['T3','T4']
                    },
                    {
                        name:'2A12',
                        texture:'军工硬铝',
                        ply:['T4','T112']
                    }
                ]},
                {serise:'3系',product:[
                    {
                        name:'3003',
                        texture:'防锈铝合金',
                        ply:['O','H112']
                    },
                    {
                        name:'3A21',
                        texture:'防锈铝合金',
                        ply:['O','H112']
                    }
                ]},
                {serise:'5系',product:[
                    {
                        name:'5052',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    },
                    {
                        name:'5083',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    },
                    {
                        name:'5754',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    },
                    {
                        name:'5A02',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    },
                    {
                        name:'5A05',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    },
                    {
                        name:'5A06',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    }
                ]},
                {serise:'6系',product:[
                    {
                        name:'6061',
                        texture:'工业硬铝',
                        ply:['T5','T6']
                    },
                    {
                        name:'6063',
                        texture:'工业硬铝',
                        ply:['T5','T6']
                    },
                    {
                        name:'6082',
                        texture:'工业硬铝',
                        ply:['T6','T651']
                    }
                ]},
                {serise:'7系',product:[
                    {
                        name:'7050',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'7075',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'7A04',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'7A09',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    }
                ]}
            ]},
            {type:'铝型材',e_t:'aluminium profile',prompt:['2024铝型材','2A12铝型材','6061铝型材','6063铝型材','6082铝型材','7075铝型材'],
                second_classify:[
                {serise:'1系',product:[
                    {
                        name:'1050',
                        texture:'工业纯铝',
                        ply:['H111','H112']
                    },
                    {
                        name:'1060',
                        texture:'工业纯铝',
                        ply:['H24','H112']
                    }
                ]},
                {serise:'2系',product:[
                    {
                        name:'2017',
                        texture:'军工硬铝',
                        ply:['T3','T4']
                    },
                    {
                        name:'2024',
                        texture:'军工硬铝',
                        ply:['T3','T4']
                    },
                    {
                        name:'2A12',
                        texture:'军工硬铝',
                        ply:['T4','T112']
                    }
                ]},
                {serise:'3系',product:[
                    {
                        name:'3003',
                        texture:'防锈铝合金',
                        ply:['H16','H112']
                    },
                    {
                        name:'3A21',
                        texture:'防锈铝合金',
                        ply:['H18','H24']
                    }
                ]},
                {serise:'5系',product:[
                    {
                        name:'5052',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    },
                    {
                        name:'5083',
                        texture:'耐腐蚀铝镁合金',
                        ply:['H26','H112']
                    },
                    {
                        name:'5754',
                        texture:'耐腐蚀铝镁合金',
                        ply:['H32','H112']
                    },
                    {
                        name:'5A02',
                        texture:'耐腐蚀铝镁合金',
                        ply:['H32','H112']
                    },
                    {
                        name:'5A05',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    },
                    {
                        name:'5A06',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    }
                ]},
                {serise:'6系',product:[
                    {
                        name:'6061',
                        texture:'工业硬铝',
                        ply:['T5','T652']
                    },
                    {
                        name:'6063',
                        texture:'工业硬铝',
                        ply:['T5','T6']
                    },
                    {
                        name:'6082',
                        texture:'工业硬铝',
                        ply:['T6','T651']
                    }
                ]},
                {serise:'7系',product:[
                    {
                        name:'7050',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'7075',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'7A04',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'7A09',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    }
                ]}
            ]},
            {type:'铝锻件',e_t:'aluminium forgings',prompt:['2024铝锻件','2A12铝锻件','6061铝锻件','6082铝锻件','5083铝锻件','7075铝锻件'],
                second_classify:[
                {serise:'1系',product:[
                    {
                        name:'1050',
                        texture:'工业纯铝',
                        ply:['H111','H112']
                    },
                    {
                        name:'1060',
                        texture:'工业纯铝',
                        ply:['H24','H112']
                    }
                ]},
                {serise:'2系',product:[
                    {
                        name:'2017',
                        texture:'军工硬铝',
                        ply:['T3','T4']
                    },
                    {
                        name:'2024',
                        texture:'军工硬铝',
                        ply:['T3','T4']
                    },
                    {
                        name:'2A12',
                        texture:'军工硬铝',
                        ply:['T4','T112']
                    }
                ]},
                {serise:'3系',product:[
                    {
                        name:'3003',
                        texture:'防锈铝合金',
                        ply:['H16','H112']
                    },
                    {
                        name:'3A21',
                        texture:'防锈铝合金',
                        ply:['H18','H24']
                    }
                ]},
                {serise:'5系',product:[
                    {
                        name:'5052',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    },
                    {
                        name:'5083',
                        texture:'耐腐蚀铝镁合金',
                        ply:['H26','H112']
                    },
                    {
                        name:'5754',
                        texture:'耐腐蚀铝镁合金',
                        ply:['H32','H112']
                    },
                    {
                        name:'5A02',
                        texture:'耐腐蚀铝镁合金',
                        ply:['H32','H112']
                    },
                    {
                        name:'5A05',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    },
                    {
                        name:'5A06',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    }
                ]},
                {serise:'6系',product:[
                    {
                        name:'6061',
                        texture:'工业硬铝',
                        ply:['T5','T652']
                    },
                    {
                        name:'6063',
                        texture:'工业硬铝',
                        ply:['T5','T6']
                    },
                    {
                        name:'6082',
                        texture:'工业硬铝',
                        ply:['T6','T651']
                    }
                ]},
                {serise:'7系',product:[
                    {
                        name:'7050',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'7075',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'7A04',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'7A09',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    }
                ]}
            ]},
            {type:'进口铝板',e_t:'import aluminium plate',prompt:['2A12进口铝板','5754进口铝板','6083进口铝板','7075进口铝板'],
                second_classify:[
                {serise:'2系',product:[
                    {
                        name:'2024',
                        texture:'军工硬铝',
                        ply:['T3','T4']
                    },
                    {
                        name:'2A12',
                        texture:'军工硬铝',
                        ply:['T4','T112']
                    }
                ]},
                {serise:'5系',product:[
                    {
                        name:'5052',
                        texture:'耐腐蚀铝镁合金',
                        ply:['H32','H112']
                    },
                    {
                        name:'5083',
                        texture:'耐腐蚀铝镁合金',
                        ply:['H26','H112']
                    },
                    {
                        name:'5754',
                        texture:'耐腐蚀铝镁合金',
                        ply:['H22','H32']
                    }
                ]},
                {serise:'6系',product:[
                    {
                        name:'6061',
                        texture:'工业硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'6063',
                        texture:'工业硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'6082',
                        texture:'工业硬铝',
                        ply:['T6','T651']
                    }
                ]},
                {serise:'7系',product:[
                    {
                        name:'7050',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'7075',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    },
                ]}
            ]},
            {type:'进口铝棒',e_t:'import aluminium rod',prompt:['2A12进口铝棒','2024进口铝棒','5083进口铝棒','6061进口铝棒','7075进口铝棒'],
                second_classify:[
                {serise:'2系',product:[
                    {
                        name:'2024',
                        texture:'军工硬铝',
                        ply:['T3','T4']
                    },
                    {
                        name:'2A12',
                        texture:'军工硬铝',
                        ply:['T4','T112']
                    }
                ]},
                {serise:'5系',product:[
                    {
                        name:'5052',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    },
                    {
                        name:'5083',
                        texture:'耐腐蚀铝镁合金',
                        ply:['O','H112']
                    }
                ]},
                {serise:'6系',product:[
                    {
                        name:'6061',
                        texture:'工业硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'6063',
                        texture:'工业硬铝',
                        ply:['T6','T651']
                    },
                    {
                        name:'6082',
                        texture:'工业硬铝',
                        ply:['T6','T651']
                    }
                ]},
                {serise:'7系',product:[
                    {
                        name:'7075',
                        texture:'航空超硬铝',
                        ply:['T6','T651']
                    }
                ]}
            ]}
        ]
export default function getProductList(req,res){
    const {categoryIndex,typeIndex,seriseIndex} = req.body
    console.log(categoryIndex,typeIndex,seriseIndex);
    // 一级请求
    if(categoryIndex !== undefined && (typeIndex == undefined && seriseIndex ==undefined)){
        // console.log('一级请求');
        let list = data[categoryIndex]
        // data[categoryIndex].first_classify.forEach(item=> {
        //     list.push(item.type)
        // });
        // console.log(list);
        res.status(200).json({list})
    }
}